openapi: 3.0.0
info:
  title: チャンネル情報BFF
  description: チャンネル情報を取得するBFF
  version: 1.0.0
servers:
  - url: https://localhost:8081
    description: チャンネル情報BFF
paths:
  /channelInfoBFF:
    get:
      tags:
        - channelInfoBFF
      operationId: getChannelInfoBFF
      summary: チャンネル情報を取得するBFF
      description: チャンネル情報を取得するBFF
      responses:
        '200':
          description: チャンネル情報を正常取得
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/channelInfoList'      
components:
  schemas:
    channelInfoList:
      description: チャンネル情報
      type: object
      properties:
        channelInfo:
          description: チャンネル情報リスト
          type: array
          items:
            $ref: '#/components/schemas/channelInfo'
    channelInfo:
      description: チャンネル情報
      type: object
      properties:
        channelId:
          type: integer
          maximum : 9
          minimum : 0
          description: チャンネルID
        channelName:
          type: string
          maxLength: 30
          description: チャンネル名