openapi: 3.0.0
info:
  title: 年月週管理登録・更新BFF
  description: 年月週管理マスタ情報を登録または更新するBFF
  version: 1.0.0
servers:
  - url: https://localhost:8081
    description: 年月週管理マスタ情報を登録または更新するBFF
paths:
  /nentsukiShuKanriBFF:
    post:
      tags:
        - nentsukiShuKanriBFF
      operationId: postProgramTorokuKoshinBFF
      summary: 年月週管理マスタ情報を登録または更新するBFF
      description: 年月週管理マスタ情報を登録または更新するBFF
      requestBody:
        description: 年月週管理マスタ情報を登録または更新するBFF
        content:
          application/json:
            schema:
              $ref: "../../TalentSearchCommon/Tables/mNentsukiShuKanri.yaml#/components/schemas/mNentsukiShuKanri"
      responses:
        '200':
          description: 登録または更新した年月週管理マスタDTOの情報
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/nentsukiShuKanriBFF'
components:
  schemas:
    nentsukiShuKanriBFF:
      description: 登録または更新した年月週管理マスタDTOの情報
      type: object
      properties:
        mNentsukiShuKanri:
          description: 年月週管理マスタDTO
          type: array
          items:
            $ref: "../../TalentSearchCommon/Tables/mNentsukiShuKanri.yaml#/components/schemas/mNentsukiShuKanri"
