openapi: 3.0.0
info:
  title: オンエア管理参照検索BFF
  description: ID、オンエア日によってオンエア管理情報を返すBFF
  version: 1.0.0
servers:
  - url: https://localhost:8081
    description: オンエア管理参照検索BFF
paths:
  /onAirKanriRefBFF:
    get:
      tags:
        - onAirKanriRefBFF
      operationId: getOnAirKanriRefBFF
      summary: ID、オンエア日によってオンエア管理情報を返すBFF
      description: ID、オンエア日によってオンエア管理情報を返すBFF
      parameters:
        - in: query
          name: id
          required: false
          description: ID
          schema:
            type: string
            maxLength: 8
        - in: query
          name: onAirDay
          required: false
          description: オンエア日
          schema:
            type: string
            format: yyyy/MM/dd
      responses:
        '200':
          description: オンエア管理情報を正常取得
          content:
            application/json:
              schema:
<<<<<<< HEAD
                $ref: '#/components/schemas/onAirKanriList'
components:
  schemas:
    onAirKanriList:
      description: オンエア管理テーブルDTO
=======
                items:
                  $ref: '#/components/schemas/onAirKanriList'
components:
  schemas:
    onAirKanriList:
      description: オンエア管理テーブルDTOの情報
>>>>>>> 9d3789c (番組参照ダイアログ、タレント参照ダイアログ、オンエア管理参照ダイアログ、年月週管理参照ダイアログ、の自動生成の準備)
      type: object
      properties:
        tOnAirKanri:
          description: オンエア管理テーブルDTO
          type: array
          items:
<<<<<<< HEAD
            $ref: "../../TalentSearchCommon/Tables/tOnAirKanri.yaml#/components/schemas/tOnAirKanri"
=======
            $ref: "../../TalentSearchCommon/Tables/tOnAirKanri.yaml#/components/schemas/tOnAirKanri"
 
>>>>>>> 9d3789c (番組参照ダイアログ、タレント参照ダイアログ、オンエア管理参照ダイアログ、年月週管理参照ダイアログ、の自動生成の準備)
