openapi: 3.0.0
info:
  title: オンエア管理情報BFF
  description: IDによってオンエア管理情報を返すBFF
  version: 1.0.0
servers:
  - url: https://localhost:8081
    description: オンエア管理情報BFF
paths:
  /onAirKanriInfoBFF/{id}:
    get:
      tags:
        - onAirKanriInfoBFF
      operationId: getOnAirKanriInfoBFF
      summary: オンエア管理情報を取得するBFF
      description: オンエア管理情報を取得するBFF
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            maxLength: 8
      responses:
        '200':
          description: オンエア管理情報を正常取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/onAirKanriList'
  /onAirKanriInfoBFF:
    post:
      tags:
        - onAirKanriInfoBFF
      operationId: postOnAirKanriInfoBFF
      summary: オンエア管理情報を登録または更新するBFF
      description: オンエア管理情報を登録または更新するBFF
      requestBody:
        description: オンエア管理情報を登録または更新するBFF
        content:
          application/json:
            schema:
              $ref: "../../TalentSearchCommon/Tables/tOnAirKanri.yaml#/components/schemas/tOnAirKanri"
      responses:
        '200':
          description: 登録または更新したオンエア管理情報
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/onAirKanriList'
components:
  schemas:
     onAirKanriList:
      description: オンエア管理テーブルDTOの情報
      type: object
      properties:
        tOnAirKanri:
          description: オンエア管理テーブルDTO
          type: array
          items:
            $ref: "../../TalentSearchCommon/Tables/tOnAirKanri.yaml#/components/schemas/tOnAirKanri"