openapi: 3.0.0
info:
  title: オンエア管理参照検索BFF
  description: ID、オンエア日によってオンエア管理情報を返すBFF
  version: 1.0.0
servers:
  - url: https://localhost:8081
    description: オンエア管理参照検索BFF
paths:
  /onAirKanriRefBFF:
    get:
      tags:
        - onAirKanriRefBFF
      operationId: getOnAirKanriRefBFF
      summary: ID、オンエア日によってオンエア管理情報を返すBFF
      description: ID、オンエア日によってオンエア管理情報を返すBFF
      parameters:
        - in: query
          name: id
          required: false
          description: ID
          schema:
            type: string
            maxLength: 8
        - in: query
          name: onAirDay
          required: false
          description: オンエア日
          schema:
            type: string
            format: yyyy/MM/dd
      responses:
        '200':
          description: オンエア管理情報を正常取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/onAirKanriRefList'
components:
  schemas:
    onAirKanriRefList:
      description: オンエア管理参照DTOの情報
      type: object
      properties:
        tOnAirKanriRef:
          description: オンエア管理参照DTO
          type: array
          items:
            $ref: "#/components/schemas/tOnAirKanriRef"
    tOnAirKanriRef:
      description: オンエア管理参照DTOの情報
      type: object
      properties:
        id:
          type: string
          maxLength: 8
          description: ID
        onAirDay:
          type: string
          format: yyyy/MM/dd
          description: オンエア日
        programId:
          type: string
          maxLength: 8
          description: 番組ID
        programName:
          type: string
          maxLength: 30
          description: 番組名
        talentId:
          type: string
          maxLength: 8
          description: タレントID
        talentName:
          type: string
          maxLength: 30
          description: タレント名
        nentsuki:
          type: integer
          maximum : 210012
          minimum : 199001
          description: 対象年月
        shu:
          type: integer
          maximum : 5
          minimum : 1
          description: 対象週
        deleteFlg:
          type: integer
          maximum : 9
          minimum : 0
          description: 論理削除フラグ
        torokuDay:
          type: string
          format: yyyy/MM/dd
          description: 登録日
        koushinDay:
          type: string
          format: yyyy/MM/dd
          description: 更新日