openapi: 3.0.0
info:
  title: 番組登録・更新BFF
  description: 番組情報を登録または更新する
  version: 1.0.0
servers:
  - url: https://localhost:8081
    description: 番組登録・更新BFF
paths:
  /programTorokuKoshinBFF:
    post:
      tags:
        - programTorokuKoshinBFF
      operationId: postProgramTorokuKoshinBFF
      summary: 番組情報を登録または更新するBFF
      description: 番組情報を登録または更新するBFF
      requestBody:
        description: 番組情報を登録または更新するBFF
        content:
          application/json:
            schema:
              $ref: "../../TalentSearchCommon/Tables/mProgram.yaml#/components/schemas/mProgram"
      responses:
        '200':
          description: 登録または更新した番組マスタ情報
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/programTorokuKoshinBFF'      
components:
  schemas:
    programTorokuKoshinBFF:
      description: 登録または更新した番組マスタ情報
      type: object
      properties:
          items:
            $ref: "../../TalentSearchCommon/Tables/mProgram.yaml#/components/schemas/mProgram"