openapi: 3.0.0
info:
  title: 番組参照検索BFF
  description: 番組ID、番組名によって番組情報を返すBFF
  version: 1.0.0
servers:
  - url: https://localhost:8081
    description: 番組参照検索BFF
paths:
  /programRefBFF:
    get:
      tags:
        - programRefBFF
      operationId: getProgramRefBFF
      summary: 番組ID、番組名によって番組情報を返すBFF
      description: 番組ID、番組名によって番組情報を返すBFF
      parameters:
        - in: query
          name: programId
          required: false
          description: 番組ID
          schema:
            type: string
            maxLength: 8
        - in: query
          name: programName
          required: false
          description: 番組名
          schema:
            type: string
            maxLength: 30
      responses:
        '200':
          description: 番組情報を正常取得
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/programInfoRefList'
components:
  schemas:
    programInfoRefList:
      description: 番組マスタ情報DTO
      type: object
      properties:
        programInfoRef:
          description: 番組マスタDTO
          type: array
          items:
            $ref: "#/components/schemas/programInfoRef"
    programInfoRef:
      description: 番組マスタ情報DTOの情報
      type: object
      properties:
        programId:
          type: string
          maxLength: 8
          description: 番組ID
        programName:
          type: string
          maxLength: 30
          description: 番組名
        channelId:
          type: integer
          maximum : 9
          minimum : 0
          description: チャンネルID
        channelKyokuId:
          type: integer
          maximum : 9
          minimum : 0
          description: チャンネル局ID
        genreId:
          type: integer
          maximum : 99
          minimum : 0
          description: ジャンルID
        deleteFlg:
          type: integer
          maximum : 9
          minimum : 0
          description: 論理削除フラグ
        torokuDay:
          type: string
          format: yyyy/MM/dd
          description: 登録日
        koushinDay:
          type: string
          format: yyyy/MM/dd
          description: 更新日
