openapi: 3.0.0
info:
  title: 週間タレント別情報BFF
  description: １週間においてのタレントごとの情報をするBFF
  version: 1.0.0
servers:
  - url: https://localhost:8081
    description: 週間タレント別情報BFF
paths:
  /shukanTalentJohoBFF:
    get:
      tags:
        - shukanTalentJohoBFF
      operationId: getShukanTalentJohoBFF
      summary: １週間においてのタレントごとの情報を返すBFF
      description: １週間においてのタレントごとの情報を返すBFF
      parameters:
        - in: query
          name: nentsuki
          required: true
          schema:
            type: integer
            maximum: 210012
            minimum: 199001
        - in: query
          name: shu
          required: true
          schema:
            type: integer
            maximum: 5
            minimum: 1
        - in: query
          name: talentName
          required: false
          schema:
            type: string
            maxLength: 30
      responses:
        '200':
          description: １週間においてのタレントごとの情報を正常取得
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/shukanTalentJohoBFF'
components:
  schemas:
    shukanTalentJohoBFF:
      description: １週間においてのタレントごとの情報
      type: object
      properties:
        talentId:
          type: string
          maxLength: 8
          description: タレントID
        talentName:
          type: string
          maxLength: 30
          description: タレント名
        shukanShutsuenProgramHonsu:
          type: integer
          maximum: 999
          minimum: 0
          description: 週間出演番組本数
        shutsuenProgramChokin:
          type: string
          maxLength: 30
          description: 出演番組（直近）
        onAirDayChokin:
          type: string
          format: yyyy/MM/dd
          description: オンエア日（直近）
        shuFrom:
          type: string
          format: yyyy/MM/dd
          description: 対象週(FROM)
        shuTo:
          type: string
          format: yyyy/MM/dd
          description: 対象週(TO)
